### ISSUE TITLE
getRelative usage : return empty array

### ISSUE THREAD

**Issue by cybele00** [B3rn475/almostjs#4]
Hello Carlo,
I've been using your lib for a while and wanted to explore extended version of model/elements.
I don't get the reason why the following code doesn't work (it return an empty array):

```
var extend = createExtender({
  type: {},
  relation: {
    "Parent": {
      relation: "hierarchy", 
      from: "child", 
      to: "parent", 
      single: true
    },
    "Children": {
      relation: "hierarchy", from: "parent", to: "child"
    }
  },
  custom: {}
});

let testModel = {
  elements: [
    { id: "bob", type: "entity", attributes: { name: "bob", age: "35" } },
    { id: "alice", type: "entity", attributes: { name: "alice", age: "31" } }
  ],
  relations: [
    { type: "hierarchy", children: "bob", parent: "alice" }
  ]
} 
let testExtendModel = extend(testModel);
console.log(testExtendModel.getChildren("alice"));
//should return bob
```

Nice work by the way!
Thanks for your help !

**Comment by B3rn475** [comment]
I think that you have a typo.
The `relation` definitions in the extender are using `"child"`, while the `relation` in your model is using `"children"`.
You need to align them.
I think that, given the 1:1 nature of a `relation` you should change the model and keep the extender configurations as they are.

Let me know if this solves it.

Thank you for linking the project ;-)
Don't hesitate to open other issues if you find problems.

**Comment by cybele00** [comment]
Ohh sorry, I was focused on something else... and not enough skilled to do proper node debugging
It's ok now ! bob is returned

Thanks for the quick reply!
Cybele

**Comment by B3rn475** [comment]
Glad to hear that `bob` is safe and sound.

We could consider to add, opt-in, a runtime check that throws an exception if the `relation` in the model is not following the configurations in the extender.

P.S. if you are building something interesting with ALMOsT.js I would love to see it, or hear about it.
If you release this project feel free to ping me, maybe in this thread. I was considering to add a list of projects which are using it..

**Comment by cybele00** [comment]
Yes!, great idea for validation !
For now, I have no ideas on what I'll be building, but I have interests in MDE to speed up development elegantly, Found EMF/Ecore 
 but too much "heavy"/complex.
If I'll build something interesting, you'll be obviously the first person to know it.

I desperatly try to reproduce yesterday success, but I failed... : 
```
var extendSimple = createExtender({
  type: {},
  relation: {
    "Parent": {
      relation: "hierarchy", 
      from: "children", 
      to: "parent", 
      single: true
    },
    "Children": {
      relation: "hierarchy", from: "parent", to: "children"
    }
  },
  custom: {}
});
let simpleModel = { 
    elements: [ 
     { id: 'p',
       type: 'entity',
       attributes: { name: "string"}
        },
     { id: 'c',
       type: 'entity',
       attributes: { name: "string"}
       } ],
  relations:
   [ 
     { relation: 'hierarchy',
       parent: 'p',
       children: 'c' }
   ]
       };
let extendedModelSimple = extendSimple(simpleModel);
console.log(extendedModelSimple.getChildren("p"));
// Return void array.... but should return "c"
```

do you find any typo ;-) ?

**Comment by B3rn475** [comment]
You have a typo in your relation.
It should be
```javascript
{ type: 'hierarchy', parent: 'p', children: 'c' }
```
and not
```javascript
{ relation: 'hierarchy', parent: 'p', children: 'c' }
```

See [almostjs-extend#relations](https://github.com/B3rn475/almostjs-extend#relations) for specifications
